# Generated by Django 2.2.16 on 2022-06-26 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220623_1405'),
        ('reviews', '0004_auto_20220623_1743'),
    ]

    operations = [
    ]
