# Generated by Django 2.2.16 on 2022-06-28 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_merge_20220627_0113'),
        ('reviews', '0005_user_password'),
    ]

    operations = [
    ]
